version: '3.9'
services:
  app:
    container_name: gosplash_app
    build:
      context: .
      dockerfile: ./.docker/app/Dockerfile
    restart: always
    tty: true
    ports:
      - 8000:8000
    volumes:
      - ./app:/go/src/app
  nginx:
    container_name: gosplash_nginx
    build:
      context: .
      dockerfile: ./.docker/nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
  mysql:
    container_name: gosplash_mysql
    build:
      context: .
      dockerfile: ./.docker/mysql/Dockerfile
    ports:
      - 3306:3306
    environment:
          MYSQL_DATABASE: $DB_DATABASE
          MYSQL_USER: $DB_USERNAME
          MYSQL_PASSWORD: $DB_PASSWORD
          MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD_WR
  minio:
    container_name: gosplash_minio
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
          MINIO_ROOT_USER: $AWS_ACCESS_KEY_ID
          MINIO_ROOT_PASSWORD: $AWS_SECRET_ACCESS_KEY
          MINIO_DEFAULT_BUCKETS: $MINIO_DEFAULT_BUCKETS
    command: server --address :9001 --console-address :9000 /data
  createbuckets:
    container_name: gosplash_minio_create_bucket
    image: minio/mc
    depends_on:
      - minio
    entrypoint: [ "" ]
    command:
      - /bin/sh
      - -c
      - |
        until (mc config host add minio http://minio:9001 $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY) do echo 'wait until add host' && sleep 1; done;
        mc mb minio/gosplash
        mc policy set public minio/gosplash