version: '3.9'
services:
  app:
    container_name: gosplash_app
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
    restart: always
    ports:
      - 8000:80000
    volumes:
      - ./app:/go/src/app
  nginx:
    container_name: gosplash_nginx
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    ports:
      - 80:80
